name: "deps-diff"
description: "Clojure dependencies differ"
author: "Hyunwoo Nam"
branding:
  icon: "package"
  color: "green"

inputs:
  base:
    required: true
    description: git/sha of base commit
    default: ${{ github.event.pull_request.base.sha }}
  project:
    required: false
    description: path of the target deps.edn
    default: "deps.edn"
  aliases:
    required: false
    description: aliases to create basis
    default: "nil"
  format:
    required: false
    description: output format. edn (default) OR markdown

outputs:
  deps_diff:
    description: output in edn format
    value: ${{ steps.diff.outputs.DEPS_DIFF }}
  exit_code:
    description: Result of command (exit code). 0, if no difference.
    value: ${{ steps.diff.outputs.EXIT_CODE }}

runs:
  using: "composite"
  steps:
    - name: Prepare java
      uses: actions/setup-java@v3
      with:
        distribution: "corretto"
        java-version: "17"

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@12.1
      with:
        cli: latest

    - name: Cache maven
      uses: actions/cache@v3
      env:
        cache-name: cache-clojure
      with:
        path: |
          ~/.m2
          ~/.gitlibs
        key: ${{ env.cache-name }}-${{ hashFiles('**/deps.edn') }}
        restore-keys: |
          ${{ env.cache-name }}-

    - name: Checkout base
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.base.sha }}

    - name: Resolve base
      shell: bash
      run: |
        clojure -X:deps tree :project '"${ inputs.project }}"' :aliases '${{ inputs.aliases }}' :format :edn > __base.edn

    - name: Checkout target
      uses: actions/checkout@v4
      with:
        clean: false

    - name: Resolve target
      shell: bash
      run: |
        clojure -X:deps tree :project '"${ inputs.project }}"' :aliases '${{ inputs.aliases }}' :format :edn > __target.edn

    - id: diff
      shell: bash
      run: |
        set +e

        DEPS_DIFF=$(clojure -Tdeps-diff namenu.tools.deps-diff/diff \
          :base '"__base.edn"' \
          :target '"__target.edn"' \
          :format :${{ inputs.format }})
        EXIT_CODE=$?

        echo "DEPS_DIFF<<EOF" >> $GITHUB_OUTPUT
        echo "$DEPS_DIFF" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

        echo "EXIT_CODE=$EXIT_CODE" >> $GITHUB_OUTPUT
        # always exit with 0
        # exit $EXIT_CODE
